### PR TITLE
CircleCI: fix go-tests/TestRequiredProtocolVersionChangeAndHalt

### LINKED ISSUE #136: CircleCI: go-tests/TestRequiredProtocolVersionChangeAndHalt failed
Error [log](https://app.circleci.com/pipelines/circleci/VJoJbnHRXJiFR13mWFvRfZ/SHyYDZiLFYMtveJSZVFKbw/75/workflows/8c45fb9a-d059-4580-94b5-b9869f515abe/jobs/1465): 

```
protocol_versions_test.go:139: 
                Error Trace:    /var/lib/circleci-runner/workdir/op-e2e/system/runcfg/protocol_versions_test.go:139
                Error:          Received unexpected error:
                                operation failed permanently after 10 attempts: verifier EL node is not closed yet
                Test:           TestRequiredProtocolVersionChangeAndHalt
```

### PR DESCRIPTION
**Pull request by syntrust**
This PR fixes https://github.com/ethstorage/optimism/issues/136. 

The test `TestRequiredProtocolVersionChangeAndHalt` is to verify that an op node can stop upon a major version upgrade. 

The issue happens because `IsURLAvailable()` returns `true` for an empty URL ("http://") when port 80 happens to be occupied by another process on the CircleCI server. However, "http://" means the op-geth instance already stopped.

### CODE REVIEW

File: op-e2e/system/runcfg/protocol_versions_test.go [hunk 1]
```diff
@@ -130,7 +130,13 @@ func TestRequiredProtocolVersionChangeAndHalt(t *testing.T) {
...
 		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
 		defer cancel()
-		available := client.IsURLAvailable(ctx, sys.NodeEndpoint("verifier").(endpoint.HttpRPC).HttpRPC())
+		url := sys.NodeEndpoint("verifier").(endpoint.HttpRPC).HttpRPC()
+		// The URL of the verifier op-geth becomes empty after it is stopped.
+		// In this case, IsURLAvailable() returns an incorrect value when port 80 happens to be occupied by another process.
+		if url == "http://" {
+			return struct{}{}, nil
+		}
+		available := client.IsURLAvailable(ctx, url)
```
Comment (qzhodl) [inline op-e2e/system/runcfg/protocol_versions_test.go:139]: Is "http://" a valid URL? If not, should we modify `client.IsURLAvailable()` to handle this validation instead of addressing the error earlier? 

Additionally, if this is a bug, should we consider submitting a fix to the upstream?

Comment (syntrust) [reply op-e2e/system/runcfg/protocol_versions_test.go:139]: I'm not sure "http://" is valid or not, at least `url.Parse(address)` in `IsURLAvailable` does not return error. 
I agree it makes sense to move this check into `IsURLAvailable`, but is also used in other places.

Comment (blockchaindevsh) [reply op-e2e/system/runcfg/protocol_versions_test.go:139]: I'd recommend to add a `Stopped() bool` method to [`EthInstance`](https://github.com/ethereum-optimism/optimism/blob/a1df3e127b82c4d290fd568bc7e1680145dab55c/op-e2e/e2eutils/services/services.go#L13), then check it by `sys.EthInstances["verifier"].Stopped()`, similar to how rollup node is checked.

Comment (syntrust) [reply op-e2e/system/runcfg/protocol_versions_test.go:139]: > I'd recommend to add a `Stopped() bool` method to [`EthInstance`](https://github.com/ethereum-optimism/optimism/blob/a1df3e127b82c4d290fd568bc7e1680145dab55c/op-e2e/e2eutils/services/services.go#L13), then check it by `sys.EthInstances["verifier"].Stopped()`, similar to how rollup node is checked.

This would require changing too much code, which could have a broader impact. I don't believe this is the right approach, especially considering that this is a rare case due to a specific environment.

Comment (blockchaindevsh) [reply op-e2e/system/runcfg/protocol_versions_test.go:139]: It's nice to have, but not necessary though. I might submit such a PR to upstream later if time permits.

**Review by blockchaindevsh — APPROVED** [review]

**Review by qzhodl — APPROVED** [review]
