### PR TITLE
fix blob index

### LINKED ISSUE #165: Derivation data source queries blob with wrong index
```log
t=2025-01-17T03:57:17+0100 lvl=warn msg="Engine temporary error" err="derivation failed: temp: failed to fetch blobs: expected hash 0x019ea44b60c55502ddf2e001b720bdc8e5a46ba76d58439be85c3e40b3b39074 for blob at index 1 but got 0x018de41a71773642404ce2d4fa7cb15fec64d2a5a8fc7647269b2cfdccef6bf4"

```

The correct blob can be found at http://88.99.30.186:3500/eth/v1/beacon/blob_sidecars/6769612?indices=2

The cause is a failed tx just before the batch tx with blob index 1:

https://sepolia.etherscan.io/txs?block=7498905&isblob=true

This blob should be counted when computing blob index in `dataAndHashesFromTxs`

### PR DESCRIPTION
**Pull request by blockchaindevsh**
Fixes https://github.com/ethstorage/optimism/issues/165 

The `symptom` is: if there's a failed blob tx before the batch blob tx, the calculated blob index will be wrong.
The reason is that originally we filter all failed transactions before scanning for batch transactions, thus the blob index will be wrong if this case happens. Fixed by combining the `filtering` and `scanning` into a single process and ensure blob index is incremented correctly for each blob tx.

### CODE REVIEW

**Comment by qizhou** [comment]
How did you test?  Any UT should be added?

**Comment by blockchaindevsh** [comment]
> How did you test? Any UT should be added?

Added a UT in 80f8669ccbc4a4a2eacce8a9b5849681cfe5d12e.

File: op-node/rollup/derive/blob_data_source.go [hunk 1]
```diff
@@ -145,13 +164,14 @@ func (ds *BlobDataSource) open(ctx context.Context) ([]blobOrCalldata, error) {
...
-func dataAndHashesFromTxs(txs types.Transactions, config *DataSourceConfig, batcherAddr common.Address, logger log.Logger) ([]blobOrCalldata, []eth.IndexedBlobHash) {
+func dataAndHashesFromTxs(txs types.Transactions, config *DataSourceConfig, batcherAddr common.Address, logger log.Logger, txSucceedMap map[common.Hash]bool) ([]blobOrCalldata, []eth.IndexedBlobHash) {
 	data := []blobOrCalldata{}
 	var hashes []eth.IndexedBlobHash
 	blobIndex := 0 // index of each blob in the block's blob sidecar
 	for _, tx := range txs {
 		// skip any non-batcher transactions or failed transactions
-		if !(isValidBatchTx(tx, config.l1Signer, config.batchInboxAddress, batcherAddr, logger)) {
+		// blobIndex needs to be incremented for both invalid batch tx and failed tx
+		if (!isValidBatchTx(tx, config.l1Signer, config.batchInboxAddress, batcherAddr, logger)) || (txSucceedMap != nil && !txSucceedMap[tx.Hash()]) {
```
Comment (syntrust) [inline op-node/rollup/derive/blob_data_source.go:175]: Consider a blob tx can be failed with successful blobs, I wonder if the following is a valid case, and we can handle it: 
the current tx is a valid batch tx but failed, while the blob it send is accessible from the beacon.

File: op-node/rollup/derive/blob_data_source.go [hunk 2]
```diff
@@ -73,6 +73,25 @@ func (ds *BlobDataSource) Next(ctx context.Context) (eth.Data, error) {
...
+	for _, receipt := range receipts {
+		if receipt.Status == types.ReceiptStatusSuccessful {
+			txSucceeded[receipt.TxHash] = true
+		}
+	}
+	return
+}
+
 // getTxSucceed returns all successful txs
 func getTxSucceed(ctx context.Context, useInboxContract bool, fetcher L1Fetcher, hash common.Hash, txs types.Transactions) (successTxs types.Transactions, err error) {
```
Comment (syntrust) [inline op-node/rollup/derive/blob_data_source.go:96]: It may not be a proper place to define `getTxSucceed` in `blob_data_source.go`.

File: op-node/rollup/derive/blob_data_source.go (hunk 1 above)
Comment (blockchaindevsh) [reply op-node/rollup/derive/blob_data_source.go:175]: It's exactly the case this PR ix fixing.

File: op-node/rollup/derive/blob_data_source.go (hunk 2 above)
Comment (blockchaindevsh) [reply op-node/rollup/derive/blob_data_source.go:96]: Even though `getTxSucceed` is only called in `calldata_source.go`, I prefer to keep `getTxSucceed` and `getTxSucceedMap` together for easier compare.

**Review by qzhodl — COMMENTED** [review]
LGTM

**Comment by qizhou** [comment]
I would suggest adding the description of the symptom and how to fix it.

**Review by qzhodl — APPROVED** [review]

**Comment by blockchaindevsh** [comment]
> I would suggest adding the description of the symptom and how to fix it.

Done in the PR description.

File: op-node/rollup/derive/blob_data_source.go (hunk 1 above)
Comment (syntrust) [reply op-node/rollup/derive/blob_data_source.go:175]: If I understand right, the case being fixed is - the current tx is NOT a valid batch tx, and it failed.
The case I asked is - the current tx is a valid batch tx, and it failed. My question is: is this possible?

Comment (blockchaindevsh) [reply op-node/rollup/derive/blob_data_source.go:175]: It's possible, but there's no difference when dealing with `invalid batch tx/failed` or `valid batch tx/failed`.

Comment (qizhou) [inline op-node/rollup/derive/blob_data_source.go:175]: It is a bit awkward if `txSucceedMap == nil` then all txs are success.

We can use `txFailedMap`, where when it is `nil`, all values will be false.

Comment (blockchaindevsh) [reply op-node/rollup/derive/blob_data_source.go:175]: I also considered that, but if some tx is not within the list , `txFailedMap[tx.Hash()]` will also be false, which means successful. It feels more defensive to ensure the tx is within the list and succesful. WDYT ?

Comment (blockchaindevsh) [reply op-node/rollup/derive/blob_data_source.go:175]: Btw there's already a comment about the nil map special case [here](https://github.com/ethstorage/optimism/blob/80f8669ccbc4a4a2eacce8a9b5849681cfe5d12e/op-node/rollup/derive/blob_data_source.go#L77).

Comment (qizhou) [reply op-node/rollup/derive/blob_data_source.go:175]: > I also considered that, but if some tx is not within the list , `txFailedMap[tx.Hash()]` will also be false, which means successful. It feels more defensive to ensure the tx is within the list and succesful. WDYT ?

That should be the bug of the program.  The program should get the correct list, no matter `txFailedMap` or `txSuccessMap`.

Comment (qizhou) [reply op-node/rollup/derive/blob_data_source.go:175]: > Btw there's already a comment about the nil map special case [here](https://github.com/ethstorage/optimism/blob/80f8669ccbc4a4a2eacce8a9b5849681cfe5d12e/op-node/rollup/derive/blob_data_source.go#L77).

The comment should also be added to `dataAndHashesFromTxs` method.

**Review by qizhou — APPROVED** [review]

File: op-node/rollup/derive/blob_data_source.go (hunk 1 above)
Comment (blockchaindevsh) [reply op-node/rollup/derive/blob_data_source.go:175]: > 
> The comment should also be added to `dataAndHashesFromTxs` method.

Done in 3188c12e192be3eb9db2d967b3011db67ef764d8.
